# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nchat.proto\"\x16\n\x07\x43hatMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t2/\n\x04\x43hat\x12\'\n\x0b\x43hatSession\x12\x08.ChatMsg\x1a\x08.ChatMsg\"\x00(\x01\x30\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHATMSG = _descriptor.Descriptor(
  name='ChatMsg',
  full_name='ChatMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ChatMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=36,
)

DESCRIPTOR.message_types_by_name['ChatMsg'] = _CHATMSG

ChatMsg = _reflection.GeneratedProtocolMessageType('ChatMsg', (_message.Message,), dict(
  DESCRIPTOR = _CHATMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatMsg)
  ))
_sym_db.RegisterMessage(ChatMsg)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ChatStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.ChatSession = channel.stream_stream(
          '/Chat/ChatSession',
          request_serializer=ChatMsg.SerializeToString,
          response_deserializer=ChatMsg.FromString,
          )


  class ChatServicer(object):

    def ChatSession(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ChatSession': grpc.stream_stream_rpc_method_handler(
            servicer.ChatSession,
            request_deserializer=ChatMsg.FromString,
            response_serializer=ChatMsg.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaChatServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ChatSession(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaChatStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ChatSession(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_Chat_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Chat', 'ChatSession'): ChatMsg.FromString,
    }
    response_serializers = {
      ('Chat', 'ChatSession'): ChatMsg.SerializeToString,
    }
    method_implementations = {
      ('Chat', 'ChatSession'): face_utilities.stream_stream_inline(servicer.ChatSession),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Chat_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Chat', 'ChatSession'): ChatMsg.SerializeToString,
    }
    response_deserializers = {
      ('Chat', 'ChatSession'): ChatMsg.FromString,
    }
    cardinalities = {
      'ChatSession': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Chat', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
