	.text
isr0:
	pushq $0
	pushq $0
	jmp common
isr1:
	pushq $0
	pushq $1
	jmp common
isr2:
	pushq $0
	pushq $2
	jmp common
isr3:
	pushq $0
	pushq $3
	jmp common
isr4:
	pushq $0
	pushq $4
	jmp common
isr5:
	pushq $0
	pushq $5
	jmp common
isr6:
	pushq $0
	pushq $6
	jmp common
isr7:
	pushq $0
	pushq $7
	jmp common
isr8:
	pushq $8
	jmp common
isr9:
	pushq $0
	pushq $9
	jmp common
isr10:
	pushq $10
	jmp common
isr11:
	pushq $11
	jmp common
isr12:
	pushq $12
	jmp common
isr13:
	pushq $13
	jmp common
isr14:
	pushq $14
	jmp common
isr15:
	pushq $0
	pushq $15
	jmp common
isr16:
	pushq $0
	pushq $16
	jmp common
isr17:
	pushq $17
	jmp common
isr18:
	pushq $0
	pushq $18
	jmp common
isr19:
	pushq $0
	pushq $19
	jmp common
isr20:
	pushq $0
	pushq $20
	jmp common
isr21:
	pushq $0
	pushq $21
	jmp common
isr22:
	pushq $0
	pushq $22
	jmp common
isr23:
	pushq $0
	pushq $23
	jmp common
isr24:
	pushq $0
	pushq $24
	jmp common
isr25:
	pushq $0
	pushq $25
	jmp common
isr26:
	pushq $0
	pushq $26
	jmp common
isr27:
	pushq $0
	pushq $27
	jmp common
isr28:
	pushq $0
	pushq $28
	jmp common
isr29:
	pushq $0
	pushq $29
	jmp common
isr30:
	pushq $0
	pushq $30
	jmp common
isr31:
	pushq $0
	pushq $31
	jmp common
isr32:
	pushq $0
	pushq $32
	jmp common
isr33:
	pushq $0
	pushq $33
	jmp common
isr34:
	pushq $0
	pushq $34
	jmp common
isr35:
	pushq $0
	pushq $35
	jmp common
isr36:
	pushq $0
	pushq $36
	jmp common
isr37:
	pushq $0
	pushq $37
	jmp common
isr38:
	pushq $0
	pushq $38
	jmp common
isr39:
	pushq $0
	pushq $39
	jmp common
isr40:
	pushq $0
	pushq $40
	jmp common
isr41:
	pushq $0
	pushq $41
	jmp common
isr42:
	pushq $0
	pushq $42
	jmp common
isr43:
	pushq $0
	pushq $43
	jmp common
isr44:
	pushq $0
	pushq $44
	jmp common
isr45:
	pushq $0
	pushq $45
	jmp common
isr46:
	pushq $0
	pushq $46
	jmp common
isr47:
	pushq $0
	pushq $47
	jmp common
isr48:
	pushq $0
	pushq $48
	jmp common
isr49:
	pushq $0
	pushq $49
	jmp common
isr50:
	pushq $0
	pushq $50
	jmp common
isr51:
	pushq $0
	pushq $51
	jmp common
isr52:
	pushq $0
	pushq $52
	jmp common
isr53:
	pushq $0
	pushq $53
	jmp common
isr54:
	pushq $0
	pushq $54
	jmp common
isr55:
	pushq $0
	pushq $55
	jmp common
isr56:
	pushq $0
	pushq $56
	jmp common
isr57:
	pushq $0
	pushq $57
	jmp common
isr58:
	pushq $0
	pushq $58
	jmp common
isr59:
	pushq $0
	pushq $59
	jmp common
isr60:
	pushq $0
	pushq $60
	jmp common
isr61:
	pushq $0
	pushq $61
	jmp common
isr62:
	pushq $0
	pushq $62
	jmp common
isr63:
	pushq $0
	pushq $63
	jmp common
isr64:
	pushq $0
	pushq $64
	jmp common
isr65:
	pushq $0
	pushq $65
	jmp common
isr66:
	pushq $0
	pushq $66
	jmp common
isr67:
	pushq $0
	pushq $67
	jmp common
isr68:
	pushq $0
	pushq $68
	jmp common
isr69:
	pushq $0
	pushq $69
	jmp common
isr70:
	pushq $0
	pushq $70
	jmp common
isr71:
	pushq $0
	pushq $71
	jmp common
isr72:
	pushq $0
	pushq $72
	jmp common
isr73:
	pushq $0
	pushq $73
	jmp common
isr74:
	pushq $0
	pushq $74
	jmp common
isr75:
	pushq $0
	pushq $75
	jmp common
isr76:
	pushq $0
	pushq $76
	jmp common
isr77:
	pushq $0
	pushq $77
	jmp common
isr78:
	pushq $0
	pushq $78
	jmp common
isr79:
	pushq $0
	pushq $79
	jmp common
isr80:
	pushq $0
	pushq $80
	jmp common
isr81:
	pushq $0
	pushq $81
	jmp common
isr82:
	pushq $0
	pushq $82
	jmp common
isr83:
	pushq $0
	pushq $83
	jmp common
isr84:
	pushq $0
	pushq $84
	jmp common
isr85:
	pushq $0
	pushq $85
	jmp common
isr86:
	pushq $0
	pushq $86
	jmp common
isr87:
	pushq $0
	pushq $87
	jmp common
isr88:
	pushq $0
	pushq $88
	jmp common
isr89:
	pushq $0
	pushq $89
	jmp common
isr90:
	pushq $0
	pushq $90
	jmp common
isr91:
	pushq $0
	pushq $91
	jmp common
isr92:
	pushq $0
	pushq $92
	jmp common
isr93:
	pushq $0
	pushq $93
	jmp common
isr94:
	pushq $0
	pushq $94
	jmp common
isr95:
	pushq $0
	pushq $95
	jmp common
isr96:
	pushq $0
	pushq $96
	jmp common
isr97:
	pushq $0
	pushq $97
	jmp common
isr98:
	pushq $0
	pushq $98
	jmp common
isr99:
	pushq $0
	pushq $99
	jmp common
isr100:
	pushq $0
	pushq $100
	jmp common
isr101:
	pushq $0
	pushq $101
	jmp common
isr102:
	pushq $0
	pushq $102
	jmp common
isr103:
	pushq $0
	pushq $103
	jmp common
isr104:
	pushq $0
	pushq $104
	jmp common
isr105:
	pushq $0
	pushq $105
	jmp common
isr106:
	pushq $0
	pushq $106
	jmp common
isr107:
	pushq $0
	pushq $107
	jmp common
isr108:
	pushq $0
	pushq $108
	jmp common
isr109:
	pushq $0
	pushq $109
	jmp common
isr110:
	pushq $0
	pushq $110
	jmp common
isr111:
	pushq $0
	pushq $111
	jmp common
isr112:
	pushq $0
	pushq $112
	jmp common
isr113:
	pushq $0
	pushq $113
	jmp common
isr114:
	pushq $0
	pushq $114
	jmp common
isr115:
	pushq $0
	pushq $115
	jmp common
isr116:
	pushq $0
	pushq $116
	jmp common
isr117:
	pushq $0
	pushq $117
	jmp common
isr118:
	pushq $0
	pushq $118
	jmp common
isr119:
	pushq $0
	pushq $119
	jmp common
isr120:
	pushq $0
	pushq $120
	jmp common
isr121:
	pushq $0
	pushq $121
	jmp common
isr122:
	pushq $0
	pushq $122
	jmp common
isr123:
	pushq $0
	pushq $123
	jmp common
isr124:
	pushq $0
	pushq $124
	jmp common
isr125:
	pushq $0
	pushq $125
	jmp common
isr126:
	pushq $0
	pushq $126
	jmp common
isr127:
	pushq $0
	pushq $127
	jmp common
isr128:
	pushq $0
	pushq $128
	jmp common
isr129:
	pushq $0
	pushq $129
	jmp common
isr130:
	pushq $0
	pushq $130
	jmp common
isr131:
	pushq $0
	pushq $131
	jmp common
isr132:
	pushq $0
	pushq $132
	jmp common
isr133:
	pushq $0
	pushq $133
	jmp common
isr134:
	pushq $0
	pushq $134
	jmp common
isr135:
	pushq $0
	pushq $135
	jmp common
isr136:
	pushq $0
	pushq $136
	jmp common
isr137:
	pushq $0
	pushq $137
	jmp common
isr138:
	pushq $0
	pushq $138
	jmp common
isr139:
	pushq $0
	pushq $139
	jmp common
isr140:
	pushq $0
	pushq $140
	jmp common
isr141:
	pushq $0
	pushq $141
	jmp common
isr142:
	pushq $0
	pushq $142
	jmp common
isr143:
	pushq $0
	pushq $143
	jmp common
isr144:
	pushq $0
	pushq $144
	jmp common
isr145:
	pushq $0
	pushq $145
	jmp common
isr146:
	pushq $0
	pushq $146
	jmp common
isr147:
	pushq $0
	pushq $147
	jmp common
isr148:
	pushq $0
	pushq $148
	jmp common
isr149:
	pushq $0
	pushq $149
	jmp common
isr150:
	pushq $0
	pushq $150
	jmp common
isr151:
	pushq $0
	pushq $151
	jmp common
isr152:
	pushq $0
	pushq $152
	jmp common
isr153:
	pushq $0
	pushq $153
	jmp common
isr154:
	pushq $0
	pushq $154
	jmp common
isr155:
	pushq $0
	pushq $155
	jmp common
isr156:
	pushq $0
	pushq $156
	jmp common
isr157:
	pushq $0
	pushq $157
	jmp common
isr158:
	pushq $0
	pushq $158
	jmp common
isr159:
	pushq $0
	pushq $159
	jmp common
isr160:
	pushq $0
	pushq $160
	jmp common
isr161:
	pushq $0
	pushq $161
	jmp common
isr162:
	pushq $0
	pushq $162
	jmp common
isr163:
	pushq $0
	pushq $163
	jmp common
isr164:
	pushq $0
	pushq $164
	jmp common
isr165:
	pushq $0
	pushq $165
	jmp common
isr166:
	pushq $0
	pushq $166
	jmp common
isr167:
	pushq $0
	pushq $167
	jmp common
isr168:
	pushq $0
	pushq $168
	jmp common
isr169:
	pushq $0
	pushq $169
	jmp common
isr170:
	pushq $0
	pushq $170
	jmp common
isr171:
	pushq $0
	pushq $171
	jmp common
isr172:
	pushq $0
	pushq $172
	jmp common
isr173:
	pushq $0
	pushq $173
	jmp common
isr174:
	pushq $0
	pushq $174
	jmp common
isr175:
	pushq $0
	pushq $175
	jmp common
isr176:
	pushq $0
	pushq $176
	jmp common
isr177:
	pushq $0
	pushq $177
	jmp common
isr178:
	pushq $0
	pushq $178
	jmp common
isr179:
	pushq $0
	pushq $179
	jmp common
isr180:
	pushq $0
	pushq $180
	jmp common
isr181:
	pushq $0
	pushq $181
	jmp common
isr182:
	pushq $0
	pushq $182
	jmp common
isr183:
	pushq $0
	pushq $183
	jmp common
isr184:
	pushq $0
	pushq $184
	jmp common
isr185:
	pushq $0
	pushq $185
	jmp common
isr186:
	pushq $0
	pushq $186
	jmp common
isr187:
	pushq $0
	pushq $187
	jmp common
isr188:
	pushq $0
	pushq $188
	jmp common
isr189:
	pushq $0
	pushq $189
	jmp common
isr190:
	pushq $0
	pushq $190
	jmp common
isr191:
	pushq $0
	pushq $191
	jmp common
isr192:
	pushq $0
	pushq $192
	jmp common
isr193:
	pushq $0
	pushq $193
	jmp common
isr194:
	pushq $0
	pushq $194
	jmp common
isr195:
	pushq $0
	pushq $195
	jmp common
isr196:
	pushq $0
	pushq $196
	jmp common
isr197:
	pushq $0
	pushq $197
	jmp common
isr198:
	pushq $0
	pushq $198
	jmp common
isr199:
	pushq $0
	pushq $199
	jmp common
isr200:
	pushq $0
	pushq $200
	jmp common
isr201:
	pushq $0
	pushq $201
	jmp common
isr202:
	pushq $0
	pushq $202
	jmp common
isr203:
	pushq $0
	pushq $203
	jmp common
isr204:
	pushq $0
	pushq $204
	jmp common
isr205:
	pushq $0
	pushq $205
	jmp common
isr206:
	pushq $0
	pushq $206
	jmp common
isr207:
	pushq $0
	pushq $207
	jmp common
isr208:
	pushq $0
	pushq $208
	jmp common
isr209:
	pushq $0
	pushq $209
	jmp common
isr210:
	pushq $0
	pushq $210
	jmp common
isr211:
	pushq $0
	pushq $211
	jmp common
isr212:
	pushq $0
	pushq $212
	jmp common
isr213:
	pushq $0
	pushq $213
	jmp common
isr214:
	pushq $0
	pushq $214
	jmp common
isr215:
	pushq $0
	pushq $215
	jmp common
isr216:
	pushq $0
	pushq $216
	jmp common
isr217:
	pushq $0
	pushq $217
	jmp common
isr218:
	pushq $0
	pushq $218
	jmp common
isr219:
	pushq $0
	pushq $219
	jmp common
isr220:
	pushq $0
	pushq $220
	jmp common
isr221:
	pushq $0
	pushq $221
	jmp common
isr222:
	pushq $0
	pushq $222
	jmp common
isr223:
	pushq $0
	pushq $223
	jmp common
isr224:
	pushq $0
	pushq $224
	jmp common
isr225:
	pushq $0
	pushq $225
	jmp common
isr226:
	pushq $0
	pushq $226
	jmp common
isr227:
	pushq $0
	pushq $227
	jmp common
isr228:
	pushq $0
	pushq $228
	jmp common
isr229:
	pushq $0
	pushq $229
	jmp common
isr230:
	pushq $0
	pushq $230
	jmp common
isr231:
	pushq $0
	pushq $231
	jmp common
isr232:
	pushq $0
	pushq $232
	jmp common
isr233:
	pushq $0
	pushq $233
	jmp common
isr234:
	pushq $0
	pushq $234
	jmp common
isr235:
	pushq $0
	pushq $235
	jmp common
isr236:
	pushq $0
	pushq $236
	jmp common
isr237:
	pushq $0
	pushq $237
	jmp common
isr238:
	pushq $0
	pushq $238
	jmp common
isr239:
	pushq $0
	pushq $239
	jmp common
isr240:
	pushq $0
	pushq $240
	jmp common
isr241:
	pushq $0
	pushq $241
	jmp common
isr242:
	pushq $0
	pushq $242
	jmp common
isr243:
	pushq $0
	pushq $243
	jmp common
isr244:
	pushq $0
	pushq $244
	jmp common
isr245:
	pushq $0
	pushq $245
	jmp common
isr246:
	pushq $0
	pushq $246
	jmp common
isr247:
	pushq $0
	pushq $247
	jmp common
isr248:
	pushq $0
	pushq $248
	jmp common
isr249:
	pushq $0
	pushq $249
	jmp common
isr250:
	pushq $0
	pushq $250
	jmp common
isr251:
	pushq $0
	pushq $251
	jmp common
isr252:
	pushq $0
	pushq $252
	jmp common
isr253:
	pushq $0
	pushq $253
	jmp common
isr254:
	pushq $0
	pushq $254
	jmp common
isr255:
	pushq $0
	pushq $255
	jmp common

	.extern __int_handler
common:
	pushq %rdi
	pushq %rsi
	pushq %rdx
	pushq %rcx
	pushq %rax
	pushq %r8
	pushq %r9
	pushq %r10
	pushq %r11
	pushq %rbx
	pushq %rbp
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %r15
	movq %rsp, %rdi
	cld
	call __int_handler
	popq %r15
	popq %r14
	popq %r13
	popq %r12
	popq %rbp
	popq %rbx
	popq %r11
	popq %r10
	popq %r9
	popq %r8
	popq %rax
	popq %rcx
	popq %rdx
	popq %rsi
	popq %rdi
	addq $0x10, %rsp
	iretq

	.global __int_entry
__int_entry:
	.quad isr0
	.quad isr1
	.quad isr2
	.quad isr3
	.quad isr4
	.quad isr5
	.quad isr6
	.quad isr7
	.quad isr8
	.quad isr9
	.quad isr10
	.quad isr11
	.quad isr12
	.quad isr13
	.quad isr14
	.quad isr15
	.quad isr16
	.quad isr17
	.quad isr18
	.quad isr19
	.quad isr20
	.quad isr21
	.quad isr22
	.quad isr23
	.quad isr24
	.quad isr25
	.quad isr26
	.quad isr27
	.quad isr28
	.quad isr29
	.quad isr30
	.quad isr31
	.quad isr32
	.quad isr33
	.quad isr34
	.quad isr35
	.quad isr36
	.quad isr37
	.quad isr38
	.quad isr39
	.quad isr40
	.quad isr41
	.quad isr42
	.quad isr43
	.quad isr44
	.quad isr45
	.quad isr46
	.quad isr47
	.quad isr48
	.quad isr49
	.quad isr50
	.quad isr51
	.quad isr52
	.quad isr53
	.quad isr54
	.quad isr55
	.quad isr56
	.quad isr57
	.quad isr58
	.quad isr59
	.quad isr60
	.quad isr61
	.quad isr62
	.quad isr63
	.quad isr64
	.quad isr65
	.quad isr66
	.quad isr67
	.quad isr68
	.quad isr69
	.quad isr70
	.quad isr71
	.quad isr72
	.quad isr73
	.quad isr74
	.quad isr75
	.quad isr76
	.quad isr77
	.quad isr78
	.quad isr79
	.quad isr80
	.quad isr81
	.quad isr82
	.quad isr83
	.quad isr84
	.quad isr85
	.quad isr86
	.quad isr87
	.quad isr88
	.quad isr89
	.quad isr90
	.quad isr91
	.quad isr92
	.quad isr93
	.quad isr94
	.quad isr95
	.quad isr96
	.quad isr97
	.quad isr98
	.quad isr99
	.quad isr100
	.quad isr101
	.quad isr102
	.quad isr103
	.quad isr104
	.quad isr105
	.quad isr106
	.quad isr107
	.quad isr108
	.quad isr109
	.quad isr110
	.quad isr111
	.quad isr112
	.quad isr113
	.quad isr114
	.quad isr115
	.quad isr116
	.quad isr117
	.quad isr118
	.quad isr119
	.quad isr120
	.quad isr121
	.quad isr122
	.quad isr123
	.quad isr124
	.quad isr125
	.quad isr126
	.quad isr127
	.quad isr128
	.quad isr129
	.quad isr130
	.quad isr131
	.quad isr132
	.quad isr133
	.quad isr134
	.quad isr135
	.quad isr136
	.quad isr137
	.quad isr138
	.quad isr139
	.quad isr140
	.quad isr141
	.quad isr142
	.quad isr143
	.quad isr144
	.quad isr145
	.quad isr146
	.quad isr147
	.quad isr148
	.quad isr149
	.quad isr150
	.quad isr151
	.quad isr152
	.quad isr153
	.quad isr154
	.quad isr155
	.quad isr156
	.quad isr157
	.quad isr158
	.quad isr159
	.quad isr160
	.quad isr161
	.quad isr162
	.quad isr163
	.quad isr164
	.quad isr165
	.quad isr166
	.quad isr167
	.quad isr168
	.quad isr169
	.quad isr170
	.quad isr171
	.quad isr172
	.quad isr173
	.quad isr174
	.quad isr175
	.quad isr176
	.quad isr177
	.quad isr178
	.quad isr179
	.quad isr180
	.quad isr181
	.quad isr182
	.quad isr183
	.quad isr184
	.quad isr185
	.quad isr186
	.quad isr187
	.quad isr188
	.quad isr189
	.quad isr190
	.quad isr191
	.quad isr192
	.quad isr193
	.quad isr194
	.quad isr195
	.quad isr196
	.quad isr197
	.quad isr198
	.quad isr199
	.quad isr200
	.quad isr201
	.quad isr202
	.quad isr203
	.quad isr204
	.quad isr205
	.quad isr206
	.quad isr207
	.quad isr208
	.quad isr209
	.quad isr210
	.quad isr211
	.quad isr212
	.quad isr213
	.quad isr214
	.quad isr215
	.quad isr216
	.quad isr217
	.quad isr218
	.quad isr219
	.quad isr220
	.quad isr221
	.quad isr222
	.quad isr223
	.quad isr224
	.quad isr225
	.quad isr226
	.quad isr227
	.quad isr228
	.quad isr229
	.quad isr230
	.quad isr231
	.quad isr232
	.quad isr233
	.quad isr234
	.quad isr235
	.quad isr236
	.quad isr237
	.quad isr238
	.quad isr239
	.quad isr240
	.quad isr241
	.quad isr242
	.quad isr243
	.quad isr244
	.quad isr245
	.quad isr246
	.quad isr247
	.quad isr248
	.quad isr249
	.quad isr250
	.quad isr251
	.quad isr252
	.quad isr253
	.quad isr254
	.quad isr255
