// various identifiers and spaces, literal booleans.

read ifik;
read while_ololo;
read endend;
read writebegin;
read iftheneles;

read y43
read a_long_name

read _____nagibator___6666______
read JAVA_STYLE_CONSTANT_NAME_VERY_LARGE
read BlOnDiE123VaRiAbLe

read READ // should be case-sensitive
read If

// empty statements
;;;;;;;;;;;;;;;;

// tabs
    												

while true 
do begin
read _read;
write _write;
end

if false then write endend else write writebegin

